name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install fontforge
        run: |
          su
          apt-get update
          apt-get install -y fontforge
          exit
      - name: Build the font
        run: fontforge -lang=ff -c 'Open("tenevil-font.svg"); Generate("tenevil-font.otf")'
      - name: Build the pdf
        run: lualatex -interaction=nonstopmode tenevil.tex && biber tenevil && lualatex -interaction=nonstopmode tenevil.tex
      - uses: actions/upload-artifact@v4
        with:
          name: table-and-font
          path: |
              tenevil.pdf
              tenevil-font.otf
